name: Generate Datas

## schedule: # execute every 12 hours
##   - cron: "* */12 * * *"
## workflow_dispatch:
  

on:
  workflow_dispatch:  # s√≥ roda manualmente na aba Actions

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    if: ${{ false }}  # hard kill do job (remove quando quiser reativar)
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: marcio-dados
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# descontinuado
# Falta configurar o branch output removi e deixei desligado o action
